### PR TITLE
Release verification script.

### PR DESCRIPTION
**Pull request by rabbah**
Example of how to use this script.

```
rcverify.sh openwhisk-client-js 'OpenWhisk JavaScript Client Library' 3.19.0
```
```
working in the following directory:
/var/folders/q9/s3th42s53d34ftd5wvcypybr0000gn/T/tmp.6t9xcMV8
fetching openwhisk-client-js-3.19.0-incubating-sources.tar.gz
fetching openwhisk-client-js-3.19.0-incubating-sources.tar.gz.asc
fetching openwhisk-client-js-3.19.0-incubating-sources.tar.gz.sha512
fetching release keys
import keys
gpg: key 72AF0CC22C4CF320: "Vincent Hou (Release manager of OpenWhisk) <houshengbo@apache.org>" not changed
gpg: key 22907064147F886E: "Dave Grove <groved@us.ibm.com>" not changed
gpg: Total number processed: 2
gpg:              unchanged: 2
unpacking tar ball
cloning scancode
Cloning into 'incubator-openwhisk-utilities'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 52 (delta 23), reused 34 (delta 15), pack-reused 0
Unpacking objects: 100% (52/52), done.
computing sha512 and validating... valid
verifying asc... valid
verifying disclaimer... valid
verifing notice... valid
verifying license... not valid (diff '/var/folders/q9/s3th42s53d34ftd5wvcypybr0000gn/T/tmp.6t9xcMV8/incubator-openwhisk-client-js-3.19.0-incubating/LICENSE.txt' '/var/folders/q9/s3th42s53d34ftd5wvcypybr0000gn/T/tmp.6t9xcMV8/LICENSE-2.0')
verifying sources have proper headers... valid
scanning for binaries... valid

run the following command to remove the scratch space:
  rm -rf '/var/folders/q9/s3th42s53d34ftd5wvcypybr0000gn/T/tmp.6t9xcMV8'
```

### CODE REVIEW

**Comment by chetanmeh** [comment]
Works as expected. Lets add a usage instruction in README.md which we can then subsequently refer to in our emails for release vote. We can use a template similar to we have for [Apache Sling][1] which refers to this script

[1]: https://sling.apache.org/documentation/development/release-management.html#starting-the-vote

**Comment by chetanmeh** [comment]
Would be good to have some users validate it in other OS like ubuntu. I validated it on Mac

**Comment by dgrove-oss** [comment]
I validated on MacOS; works for me as well.

 Do we want to add the README section in this PR or in a follow up?

**Comment by chetanmeh** [comment]
I tried it with a linux image it works fine. So expect it to work on linux setups if required dependencies are present (curl, git, gnupg etc)

```bash
$ docker run --rm  -it openwhisk/ow-utils
$ wget https://raw.githubusercontent.com/apache/incubator-openwhisk-release/2160bd0af66fe40c5e0c07773b69311bebd2e00b/rcverify.sh
$ chmod +x rcverify.sh
$ ./rcverify.sh openwhisk-package-alarms 'OpenWhisk Package Alarms' 2.0.0 rc2
working in the following directory:
/tmp/tmp.6Ba3xgUSKi
fetching openwhisk-package-alarms-2.0.0-incubating-sources.tar.gz
fetching openwhisk-package-alarms-2.0.0-incubating-sources.tar.gz.asc
fetching openwhisk-package-alarms-2.0.0-incubating-sources.tar.gz.sha512
fetching release keys
import keys
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 72AF0CC22C4CF320: public key "Vincent Hou (Release manager of OpenWhisk) <houshengbo@apache.org>" imported
gpg: key 22907064147F886E: public key "Dave Grove <groved@us.ibm.com>" imported
gpg: Total number processed: 2
gpg:               imported: 2
unpacking tar ball
cloning scancode
Cloning into 'incubator-openwhisk-utilities'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 52 (delta 23), reused 34 (delta 15), pack-reused 0
Unpacking objects: 100% (52/52), done.
computing sha512 and validating... passed
verifying asc... passed
verifying disclaimer... passed
verifing notice... passed
verifying license...
verifying sources have proper headers... passed
scanning for binaries... failed (/tmp/tmp.6Ba3xgUSKi/incubator-openwhisk-package-alarms-2.0.0-incubating/package.json)
scanning for archives... passed
scanning for packages... passed

run the following command to remove the scratch space:
  rm -rf '/tmp/tmp.6Ba3xgUSKi'

```

So once we commit this we may add this script to ow-utils docker image and then users can simply run the command without bothering about required dependencies present locally (specially python for scan utilities)

```
docker run --rm  -it openwhisk/ow-utils rcverify openwhisk-package-alarms 'OpenWhisk Package Alarms' 2.0.0 rc2
```

**Comment by rabbah** [comment]
> Do we want to add the README section in this PR or in a follow up?

ok give me some time ill do it here.

**Comment by rabbah** [comment]
I've amended the release instructions, using the Sling docs as a model and adapting for our past votes. https://github.com/apache/incubator-openwhisk-release/blob/7169cb666cd00194d9d92fc98605e82a92a02a19/docs/release_instructions.md#release-distribution-requirements

**Pull request closed without merging**
